### ISSUE TITLE
Incorrect duration if the calculation takes more than a day

### ISSUE THREAD

**Issue by egofer** [Arpapiemonte/openoise-map#10]
The duration of the process is not correct if it lasts more than a day, as can be seen in the screenshot.

![Screenshot_20220424_181036](https://user-images.githubusercontent.com/3096716/164986084-e236067a-f718-4e21-bf59-125f4316e3bd.png)

**Comment by Arpapiemonte** [comment]
Thanks for the report. Yesterday we have released a new version of Openoise that works with QGIS 3.22 or higher. The new plugin has new features and shouldn't have the problem you reported to us. Your faithfully
