### ISSUE TITLE
[Feature request] Add electric vehicles

### ISSUE THREAD

**Issue by Art-Ev** [Arpapiemonte/openoise-map#11]
Hi,

How complex would it be to integrate electric vehicles to opeNoise plugin ? Is it possible to juste create a new class and complete Road_params.xml ?

Some documentation here : https://hal.archives-ouvertes.fr/hal-01355872/file/doc00025192.pdf

**Comment by Arpapiemonte** [comment]
Thanks for the tip, very interesting. We did not know this document. Yesterday we released a new version of Openoise that works with QGIS 3.22 or later. The new plugin has new features and shouldn't have the problem you reported to us. We will be working on further developments in the coming months and will try to implement electric vehicles as well as you have suggested.  Your faithfully.
