### ISSUE TITLE
Porting to QGIS 3 is in process?

### ISSUE THREAD

**Issue by pierluigiderosa** [Arpapiemonte/openoise-map#3]
Is the porting to QGIS 3 in program?
Maybe if you like I can provide an help

Thanks

**Comment by Arpapiemonte** [comment]
Hi Pierluigi,
the porting is an our goal, but we have not yet planned when.
We are very happy if you can give us a hand!

**Comment by pierluigiderosa** [comment]
Good to know

I can do the porting in my fork and ask for a pull request

Regards
Pierluigi

Il Mar 11 Set 2018, 11:27 Arpapiemonte <notifications@github.com> ha
scritto:
