### ISSUE TITLE
 QgsSpatialIndex.insertFeature() is deprecated

### ISSUE THREAD

**Issue by tatjabecker** [Arpapiemonte/openoise-map#7]
Hi, I tested the plugin with your test datasets. However when I want to calculate noise levels using the roads datasets the following message is shown in my log messages panel in QGIS: 

WARNING    warning:C:/Users/AO/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\opeNoise\tools\on_CreateEmissionPoints.py:58: DeprecationWarning:
             
             QgsSpatialIndex.insertFeature() is deprecated
             
             
             traceback: File "C:/Users/AO/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\opeNoise\opeNoise.py", line 164, in CalculateNoiseLevels_show
              d.exec_()
              File "C:/Users/AO/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\opeNoise\tools\do_CalculateNoiseLevels.py", line 778, in accept
              on_CalculateNoiseLevels.run(settings,self.progress_bars)
              File "C:/Users/AO/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\opeNoise\tools\on_CalculateNoiseLevels.py", line 862, in run
              receiver_feat_new_fields = calc(progress_bars,receiver_layer,source_pts_layer,source_roads_layer,settings,level_field_index,obstacles_layer,rays_writer,diff_rays_writer)
              File "C:/Users/AO/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\opeNoise\tools\on_CalculateNoiseLevels.py", line 310, in calc
              on_CreateEmissionPoints.run(source_roads_layer.source(),receiver_layer.source(),emission_pts_roads_layer_path,research_ray)
              File "C:/Users/AO/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\opeNoise\tools\on_CreateEmissionPoints.py", line 58, in run
              receivers_spIndex.insertFeature(receivers_feat)

P.S. I am new to QGIS and Github.

**Comment by tatjabecker** [comment]
I just fixed the problem by downgrading to QGIS version below 3.4

**Comment by Arpapiemonte** [comment]
Hi tatjabecker,
we tested our plugin only with the QGIS stable versions and recommended to use those versions.
Thanks to try to use it!

**Comment by tatjabecker** [comment]
Thank you for creating this very useful model! 

Where can I find more information about the model, other than the information already provided within the plugin in QGIS and on github,  or on  [your website](https://www.onegis.it/2019/02/14/openoise-una-breve-dimostrazione-di-utilizzo/)? And is there a way that the model takes the height of the buildings/obstacles in to account when calculating noise?

**Comment by Arpapiemonte** [comment]
Sorry but we haven't a dedicate website. 
In the web you can found this article in italian language, I hope can help you:
http://www.arpa.piemonte.it/arpa-comunica/events/eventi-2018/OpeNoisemap.pdf/at_download/file
