### ISSUE TITLE
Create receiver points generates unexpected result

### ISSUE THREAD

**Issue by dortheimer** [Arpapiemonte/openoise-map#8]
Hello,
I have just tried to use the plugin.
The first thing I did was to extract some building polygons from OSM.
This extracted layer was the input for the "Create Receiver Points" function. However, the function generated unexpected results as can be viewed in the screenshot.
I'm not sure this is a bug, but I have used the plugin following the documentation and I could not find a workaround.
Thank you for reading this.

The OSM extraction:
[oryehuda.zip](https://github.com/Arpapiemonte/openoise-map/files/5323918/oryehuda.zip)

Receiver point layer:
[receiver.zip](https://github.com/Arpapiemonte/openoise-map/files/5323922/receiver.zip)

Screenshot:
![Screenshot from 2020-10-04 20-47-48](https://user-images.githubusercontent.com/3685757/95022995-28cdf200-0683-11eb-8e7d-e981035facf2.png)

**Comment by fdamo** [comment]
Hello, 
it may be the reference system of the building layer. 
Before running the "Create Receiver Points" function, make sure the input layer has a projected CRS, epsg:2039 for instance. Regards
