### ISSUE TITLE
Cannot select building layer Creating reciever points

### ISSUE THREAD

**Issue by dwastberg** [Arpapiemonte/openoise-map#9]
I've installed the plugin via QGIS (version 3.18.1), loaded the buildings layer from the sample data set and opened the Create Receiver Points dialog. However the Buildings layer isn't showing up in the Buildings Layer dropdown so I cannot select it (or any layer) to continue.

Any idea what might be causing this?

**Comment by dgatngala** [comment]
I'm having the same issue; the drop down lists in the input tab (calculate noise levels) is not working.

**Comment by Arpapiemonte** [comment]
Hi guys, sorry for the late.
This bug is fixed by version 1.4, published today!
